### ISSUE TITLE
Mage_Catalog_Model_Product_Image is not rewrited on CE 1.9.1.1

### ISSUE THREAD

**Issue by kanevbg** [magento-hackathon/Perfect_Watermarks#15]
Due that module seems to be not working. Again uses the GD2 adapter

**Comment by datenbrille** [comment]
Mhhh, can you give some more hints?

**Comment by kanevbg** [comment]
I actually have not tested in on clean project. Let me do so and I will come back with response.

**Comment by kanevbg** [comment]
I have tested it on clean Magento 1.9.2.0 and it is working as expected I guess the problem I have reported was project specific. Maybe safe to close.
