### ISSUE TITLE
Selected library is not installed

### ISSUE THREAD

**Issue by sabaqahmad** [magento-hackathon/Perfect_Watermarks#20]
when i upload plugin files and activate plugin then i face issue.
Selected library is not installed

please help me how can i resolve this issue

**Comment by yanavit** [comment]
Same issue. Magento 1.9.2.2

**Comment by peterjaap** [comment]
See this; https://github.com/magento-hackathon/Perfect_Watermarks/blob/e17f63314c246c9f428c4146a68f6a44ad3dc513/src/app/code/community/FireGento/PerfectWatermarks/Model/System/Config/Adapter.php#L13

It means the image adapter is not installed, probably GD2 or Imagick. 

Google on 'php install gd2' or 'php install imagick' to figure out how to install/enable it.
